# -*- encoding: utf-8 -*-
#
#  anasysdoc.py
#
#  Copyright 2017 Cody Schindler <cschindler@anasysinstruments.com>
#
#  This program is the property of Anasys Instruments, and may not be
#  redistributed or modified without explict permission of the author.

import xml.etree.ElementTree as ET   #for parsing XML
import gzip                          #for unzipping .axz files
import os
import anasysfile
import heightmap
import re

class AnasysDoc(anasysfile.AnasysFile):
    """Object for holding document data in a file generated by Analysis Studio"""
    def __init__(self, f_name):
        anasysfile.AnasysFile.__init__(self)
        self._skip_tags = {'HeightMaps':{},
                           'RenderedSpectra':{},
                           'SpectraChannelViews':{}}
        #1. get etree object from xml and convert to attributes
        doc_root = self._get_etree(f_name)
        self._convert_tags(doc_root)
        self.HeightMaps = self._get_height_maps(doc_root.find('HeightMaps'))
        #3. pull out Spectra
        #4. pull out anything else important

    def _get_height_maps(self, maps):
        """Takes an iterable of Height Maps, and returns a dict of HeightMap objects"""
        mapdict = {}
        for _map in maps:
            key = _map.get('Label')
            key = self._check_key(key, mapdict)
            mapdict[key] = heightmap.HeightMap(_map)
        return mapdict

    def _get_extension(self, _f_path):
        """Returns the extension of a file, given the file path"""
        ext = os.path.splitext(_f_path)[1][1:].lower()
        return ext

    def _check_path(self, _f_path):
        """Checks for errors with file existance and type"""
        if not os.path.isfile(_f_path):
            raise FileNotFoundError()
        if not (_f_path.lower().endswith(".axz") or _f_path.lower().endswith(".axd")):
            raise ValueError("File type must be .axz or .axd")

    def _get_etree(self, f_name):
        """Main function for reading in data from axz or axd files and returns a top-level etree object"""
        #get complete file path
        self._f_path = os.path.abspath(f_name)
        #check that file is kosher
        self._check_path(self._f_path)
        #get the file extension
        ext = self._get_extension(self._f_path)
        #get the xml data from axz or axd
        if ext == 'axz':
            f_xml = self._open_axz(self._f_path)
        else:
            f_xml = self._open_axd(self._f_path)
        return f_xml.root

    def _strip_namespace(self, f_data):
        """strips annoying xmlns data that elementTree auto-prepends to all element tags"""
        for _, el in f_data:
            el.tag = el.tag.split('}', 1)[1] #strip namespaces from tags
        return f_data

    def _open_axd(self, _f_path):
        """Opens an axd file and returns its content as an ElementTree object"""
        f_data = ET.iterparse(_f_path)
        f_data = self._strip_namespace(f_data)
        return f_data #returns an ET.iterparse object

    def _open_axz(self, _f_path):
        """Opens an axz file and returns its content as an ElementTree object"""
        with gzip.open(_f_path) as f:
            f_data = ET.iterparse(f)
            f_data = self._strip_namespace(f_data)
        return f_data #returns an ET.iterparse object

def read(f):
    x = AnasysDoc(f)
    return x
